<?php
/**
 * Jamroom 5 xxBootstrap skin
 *
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Home';
$lang[2]  = 'create';
$lang[3]  = 'account';
$lang[4]  = 'profile';
$lang[5]  = 'logout';
$lang[6]  = 'login';
$lang[7]  = 'welcome to';
$lang[8]  = 'site';
$lang[9]  = 'News';
$lang[10] = 'Blog';
$lang[11] = 'newest';
$lang[12] = 'profiles';
$lang[13] = 'Audio';
$lang[14] = 'Videos';
$lang[15] = 'YouTube';
$lang[16] = 'ACP';
$lang[17] = 'dashboard';
$lang[18] = 'pages';
$lang[19] = 'Events';
$lang[20] = 'menu';
$lang[21] = 'featured';
$lang[22] = 'all';
$lang[23] = 'see all';
$lang[24] = 'search';
$lang[25] = 'Change Image';
$lang[26] = 'find new audio';
$lang[27] = 'search activity stream';
$lang[28] = 'Activity Logs';
$lang[29] = 'Reset Cache';
$lang[30] = 'Reset Image Cache';
$lang[31] = 'Integrity Check';
$lang[32] = 'Banned Items';
$lang[33] = 'Skin Menu Editor';
$lang[34] = 'Create Sitemap';
$lang[35] = 'System Check';
$lang[36] = 'Developer Tools';
$lang[37] = 'System Tools';
$lang[38] = 'Skin Settings';
$lang[39] = 'views';
$lang[40] = 'SoundCloud';
$lang[41] = 'Vimeo';
$lang[42] = 'Blogs';
$lang[43] = 'Latest Followers';
$lang[44] = 'About';
$lang[45] = 'Profile Stats';
$lang[46] = 'Recently Rated';
$lang[47] = 'Influences';
$lang[48] = 'Latest Comments';
$lang[49] = 'Profile Quota Browser';
$lang[50] = 'User Accounts';
$lang[51] = 'activity feed';
$lang[52] = 'Profile Browser';
$lang[53] = 'Who\'s Online';
$lang[54] = 'Users';
